### ISSUE TITLE
Error in install loop, ...Volume-Key-Selector/tools//keycheck: not found

### ISSUE THREAD

**Issue by sourcevault** [ImSpiDy/X-Charge-Mode#2]
getting this error, what do ?

```
- Copying zip to temp directory
- Installing X-Charge-Mode-X1.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
***************
  X Charge Mode  
 by SpiDyX027 
***************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: system/bin/XCharge
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: system/bin/XCharge
**************************************
*   MMT Extended by Zackptg5 @ XDA   *
**************************************
 
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
  inflating: Custom/README.md
  inflating: system/bin/XCharge
  inflating: common/install.sh
  inflating: service.sh
  inflating: Custom/XC_Switch.sh
   creating: common/addon/
   creating: common/addon/Volume-Key-Selector/
   creating: common/addon/Volume-Key-Selector/tools/
   creating: common/addon/Volume-Key-Selector/tools/arm/
  inflating: common/addon/Volume-Key-Selector/tools/arm/keycheck
  inflating: common/addon/Volume-Key-Selector/install.sh
  inflating: customize.sh
  inflating: system.prop
  inflating: LICENSE
  inflating: uninstall.sh
 
- Running Addons -
  Running Volume-Key-Selector...
- Vol Key Test
   Press a Vol Key:
Terminated
   Try again:
timeout: can't execute 'keycheck': No such file or directory
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/install.sh: line 39: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/tools//keycheck: not found
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/install.sh: line 40: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/tools//keycheck: not found
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/install.sh: line 39: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/tools//keycheck: not found
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/install.sh: line 40: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/tools//keycheck: not found
  ! Legacy device detected! Using old keycheck method
 
- Vol Key Programming -
  Press Vol Up Again:
  Press Vol Down
- Removing old files
- Installing

-  Devices : missi 

-  Android Version : 13 

-  Kernel : 5.15.133-Evenstar 


-  Volume Up = Next & Volume Down = Select 

-  Charging Modes ( Can be Switched with FKM / Termux ) 

-  1. Slow | 1600mA/42°C

-  2. Medium | 2325mA/44°C

-  3. Fast | 3000mA/46°C

-  Select : 
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/XCM/common/install.sh: line 39: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/tools//keycheck: not found
```

**Comment by ImSpiDy** [comment]
> getting this error, what do ?
> 
> ```
> - Copying zip to temp directory
> - Installing X-Charge-Mode-X1.zip
> - Current boot slot: _a
> - Device is system-as-root
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
>   inflating: module.prop
> ***************
>   X Charge Mode  
>  by SpiDyX027 
> ***************
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
>   inflating: customize.sh
> *******************
>  Powered by Magisk 
> *******************
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
>   inflating: system/bin/XCharge
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
>   inflating: system/bin/XCharge
> **************************************
> *   MMT Extended by Zackptg5 @ XDA   *
> **************************************
>  
> - Extracting module files
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
>   inflating: module.prop
>   inflating: Custom/README.md
>   inflating: system/bin/XCharge
>   inflating: common/install.sh
>   inflating: service.sh
>   inflating: Custom/XC_Switch.sh
>    creating: common/addon/
>    creating: common/addon/Volume-Key-Selector/
>    creating: common/addon/Volume-Key-Selector/tools/
>    creating: common/addon/Volume-Key-Selector/tools/arm/
>   inflating: common/addon/Volume-Key-Selector/tools/arm/keycheck
>   inflating: common/addon/Volume-Key-Selector/install.sh
>   inflating: customize.sh
>   inflating: system.prop
>   inflating: LICENSE
>   inflating: uninstall.sh
>  
> - Running Addons -
>   Running Volume-Key-Selector...
> - Vol Key Test
>    Press a Vol Key:
> Terminated
>    Try again:
> timeout: can't execute 'keycheck': No such file or directory
> /data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/install.sh: line 39: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/tools//keycheck: not found
> /data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/install.sh: line 40: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/tools//keycheck: not found
> /data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/install.sh: line 39: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/tools//keycheck: not found
> /data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/install.sh: line 40: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/tools//keycheck: not found
>   ! Legacy device detected! Using old keycheck method
>  
> - Vol Key Programming -
>   Press Vol Up Again:
>   Press Vol Down
> - Removing old files
> - Installing
> 
> -  Devices : missi 
> 
> -  Android Version : 13 
> 
> -  Kernel : 5.15.133-Evenstar 
> 
> 
> -  Volume Up = Next & Volume Down = Select 
> 
> -  Charging Modes ( Can be Switched with FKM / Termux ) 
> 
> -  1. Slow | 1600mA/42°C
> 
> -  2. Medium | 2325mA/44°C
> 
> -  3. Fast | 3000mA/46°C
> 
> -  Select : 
> /data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/XCM/common/install.sh: line 39: /data/adb/modules_update/XCM/common/addon/Volume-Key-Selector/tools//keycheck: not found
> ```

try X2

**Comment by sourcevault** [comment]
> try X2

where do I download X2 ? it's not there in the release page.

**Comment by ImSpiDy** [comment]
> > try X2
> 
> where do I download X2 ? it's not there in the release page.

https://www.pling.com/p/1611733/
